### ISSUE TITLE
iOS 13 dark mode issue

### ISSUE THREAD

**Issue by tcvdw1605** [OutSystems/docs-product#28]
It seems that there's an issue on iOS 13 when using dark mode. Status bar text remain white. Even when the style is set to default and the background is white.

**Comment by tcvdw1605** [comment]
[https://github.com/apache/cordova-plugin-statusbar/issues/148#issuecomment-538558631](https://github.com/apache/cordova-plugin-statusbar/issues/148#issuecomment-538558631)

**Comment by pedrosousa** [comment]
Thanks for the information! We added a "Known Issues" section to the following topic:
https://github.com/OutSystems/docs-product/blob/master/src/deliver-mobile/customize-mobile-app/customize-the-application-status-bar.md

**Comment by FranciscoLains** [comment]
Is there still no solution for this? I'm developing an App specific for IOS and all my costumers still complaining about the status bar problem. Even the ios14 continue with that issue.

**Comment by pedrosousa** [comment]
Hi @FranciscoLains,
It's still a known issue. I've contacted our development team and, unfortunately, at the moment we can't provide an expected date for having the issue resolved.

**Comment by sullltan123** [comment]
Thanks bro..It good action 👍
