### ISSUE TITLE
List Sort

### ISSUE THREAD

**Issue by thekingofspain** [OutSystems/docs-product#49]
https://github.com/OutSystems/docs-product/blob/master/src/ref/apis/auto/system-actions.md#ListSort

The third example in ListSort is confusing and unclear:
 
> ListSort(OfficeEmployeesList, Employee.Name + " " + Office.Name)
> 
> Sorts OfficeEmployeesList (a list of Employee and Office records) by the employee name and office name. If employees work in multiple offices then this sorted list will have the employee _records_ in the different offices displayed consecutively in ascending order of both their own names and the names of the offices.

Is Record the correct word above?

Please define the Entities used in this example and the object being passed in the ListSort.List parameter.

Note when I attempt to use the ListSort on a List of Structures, I get the following error:   Failed to compare two elements in the array.  Does the list item have to be a record type when using an Entity Type or Structure Type?

I do not have access to the ListSort source so I can not see what its expecting and the documentation, though quite informative for OutSystems, still is missing the specifics that I in order to call the method successfully.

**Comment by pedrosousa** [comment]
Hi @thekingofspain ,

Thank you for your feedback.

We improved the text you mention, to make it more clear.
We also checked if you can use ListSort for lists of Entities or Structures, and in fact, you can.

Did you double-check your ListSort call to make sure that it mentions existing attributes of that Structure?

**Comment by pedrosousa** [comment]
Closing this issue since we got no additional feedback.
