### ISSUE TITLE
Is_Active section Update

### ISSUE THREAD

**Issue by mikejosephson** [OutSystems/docs-product#90]
Section on Is_Active should be updated to be a little more clear. Is_Active is automatically detected if specified as "Is_Active" on the entity, otherwise it needs to be explicitly defined in the entities advanced properties. The way this is currently phrased this information is implied but not explicitly stated. It will make a little more sense if this section is expanded upon.

**Comment by claudiacarpinteiro** [comment]
Hello @mikejosephson ,

Thank you for sending this over. We have reviewed that section to make it more clear. [Have a look](https://success.outsystems.com/Documentation/11/Getting_started/Service_Studio_Tips_and_Tricks#Create_an_Aggregate_from_an_Entity). 
Keep them coming! :)
